version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: pg-multidb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__InternalDb: Host=postgres;Port=5432;Database=internal;Username=postgres;Password=postgres
      ConnectionStrings__ExternalDb: Host=postgres;Port=5432;Database=external;Username=postgres;Password=postgres

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pg_data:
