using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations.Internal
{
    /// <inheritdoc />
    public partial class ConvertIdsToKey : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
        ALTER TABLE "Rules"
        ALTER COLUMN "id" DROP IDENTITY IF EXISTS;
    """);
            migrationBuilder.Sql("""
        ALTER TABLE "Rules"
        ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
    """);

            migrationBuilder.Sql("""
        ALTER TABLE "RuleFullNames"
        ALTER COLUMN "id" DROP IDENTITY IF EXISTS;
    """);
            migrationBuilder.Sql("""
        ALTER TABLE "RuleFullNames"
        ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
    """);

            migrationBuilder.Sql("""
        ALTER TABLE "RuleSubstrings"
        ALTER COLUMN "id" DROP IDENTITY IF EXISTS;
    """);
            migrationBuilder.Sql("""
        ALTER TABLE "RuleSubstrings"
        ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
    """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "Rules"
                ALTER COLUMN "id" DROP IDENTITY IF EXISTS;
            """);
            migrationBuilder.Sql("""
                ALTER TABLE "RuleFullNames"
                ALTER COLUMN "id" DROP IDENTITY IF EXISTS;
            """);
            migrationBuilder.Sql("""
                ALTER TABLE "RuleSubstrings"
                ALTER COLUMN "id" DROP IDENTITY IF EXISTS;
            """);
        }
    }
}
